# $$\text{Caso Netflix - EDA}$$

# 0. Importación de librerías

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

# 1. Cargar datasets

In [2]:
import os
print("Python is looking in:", os.getcwd())
print("Files available here:", os.listdir('.'))

Python is looking in: c:\Users\HP ENVY\Documents\Maestria_MINE\SEMESTRE 4\1.LAB CASOS--Lukaz\CLASE 1\notebooks
Files available here: ['EDA.ipynb', 'models.ipynb', 'pruebas.ipynb']

In [3]:
dfcac_merged_updated_data = pd.read_csv("../data/raw/netflix_cac_merged_updated_data.csv")
dfcac_merged_updated_data.name = "dfcac_merged_updated_data"

dfinteractions_data = pd.read_csv("../data/raw/netflix_interactions_data.csv")
dfinteractions_data.name = "dfinteractions_data"

dfpayments_data = pd.read_csv("../data/raw/netflix_payments_data.csv")
dfpayments_data.name = "dfpayments_data"

dfsubscriptions_data = pd.read_csv("../data/raw/netflix_subscriptions_data.csv")
dfsubscriptions_data.name = "dfsubscriptions_data"

dfusers_data = pd.read_csv("../data/raw/netflix_users_data.csv")
dfusers_data.name = "dfusers_data"

# 2. Exploración básica de Dataframes

In [4]:
listadfs = [dfcac_merged_updated_data, dfinteractions_data, dfpayments_data, dfsubscriptions_data, dfusers_data]

> **Información general de cada DataFrame**

- Se puede crear una único dataframe a nivel de `UserID`
- Se debe revisar los registros vacíos de `dfinteractions_data["ContentGenre"]` -> ¿son válidos?

In [5]:
# Información general de cada DataFrame
for df in listadfs:
    print("DataFrame name:", df.name if hasattr(df, 'name') else "Unnamed DataFrame")
    print("DataFrame shape:", df.shape)
    print(df.info())
    print("\n" + "-"*50 + "\n")

DataFrame name: dfcac_merged_updated_data
DataFrame shape: (5141, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5141 entries, 0 to 5140
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CampaignID     5141 non-null   int64
 1   UserID         5141 non-null   int64
 2   CampaignName   5141 non-null   object
 3   CampaignCost   5141 non-null   int64
 4   UsersAcquired  5141 non-null   int64
 5   CAC            5141 non-null   float64
dtypes: float64(1), int64(4), object(1)
memory usage: 241.1+ KB
None

--------------------------------------------------

DataFrame name: dfinteractions_data
DataFrame shape: (3430, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3430 entries, 0 to 3429
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UserID           3430 non-null   int64
 1   InteractionDate  3430 non-null   object
 2   InteractionType  3430 non-null   object
 3   ContentGenre     1726 non-null   object
dtypes: int64(1), object(3)
memory usage: 107.3+ KB
None

--------------------------------------------------

DataFrame name: dfpayments_data
DataFrame shape: (2524, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2524 entries, 0 to 2523
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   UserID         2524 non-null   int64
 1   PaymentDate    2524 non-null   object
 2   PaymentAmount  2524 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 59.3+ KB
None

--------------------------------------------------

DataFrame name: dfsubscriptions_data
DataFrame shape: (200, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   UserID            200 non-null    int64
 1   RegistrationDate  200 non-null    object
 2   EndDate           200 non-null    object
 3   DurationMonths    200 non-null    int64
 4   CancelReason      200 non-null    object
 5   PlanType          200 non-null    object
dtypes: int64(2), object(4)
memory usage: 9.5+ KB
None

--------------------------------------------------

DataFrame name: dfusers_data
DataFrame shape: (200, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   UserID            200 non-null    int64
 1   Gender            200 non-null    object
 2   Age               200 non-null    int64
 3   Location          200 non-null    object
 4   RegistrationDate  200 non-null    object
dtypes: int64(2), object(3)
memory usage: 7.9+ KB
None

--------------------------------------------------

> **Muestra de filas de cada dataframe**

- Se debe ajustar a formato `datetime` las variables con fechas:
    - InteractionDate
    - PaymentDate
    - RegistrationDate <- dfsuscriptions_data
    - RegistrationDate <- dfusers_data
    - EndDate

In [6]:
# Muestra de filas de cada dataframe
for df in listadfs:
    print("DataFrame name:", df.name if hasattr(df, 'name') else "Unnamed DataFrame")
    print(df.head(5))
    print("\n" + "-"*50 + "\n")

DataFrame name: dfcac_merged_updated_data
   CampaignID  UserID                                       CampaignName  \
0           1       1  Social Media Blitz: Targeted ads on Instagram ...
1           1       2  Social Media Blitz: Targeted ads on Instagram ...
2           1       3  Social Media Blitz: Targeted ads on Instagram ...
3           1       4  Social Media Blitz: Targeted ads on Instagram ...
4           1       5  Social Media Blitz: Targeted ads on Instagram ...

   CampaignCost  UsersAcquired        CAC
0         25795            408  63.223039
1         25795            408  63.223039
2         25795            408  63.223039
3         25795            408  63.223039
4         25795            408  63.223039

--------------------------------------------------

DataFrame name: dfinteractions_data
   UserID InteractionDate InteractionType ContentGenre
0       1      2023-04-04    Content View     Thriller
1       1      2023-01-30    Content View       Comedy
2       1      2023-02-16    Help Request          NaN
3       1      2022-09-25    Help Request          NaN
4       1      2022-12-18    Help Request          NaN

--------------------------------------------------

DataFrame name: dfpayments_data
   UserID PaymentDate  PaymentAmount
0       1  2022-08-11           9.99
1       1  2022-09-10           9.99
2       1  2022-10-10           9.99
3       1  2022-11-09           9.99
4       1  2022-12-09           9.99

--------------------------------------------------

DataFrame name: dfsubscriptions_data
   UserID RegistrationDate     EndDate  DurationMonths     CancelReason  \
0       1       2022-08-11  2022-12-09               4  No cancellation
1       2       2022-09-07  2024-02-29              18  No cancellation
2       3       2022-05-27  2023-02-21               9  No cancellation
3       4       2022-04-06  2024-01-26              22  No cancellation
4       5       2022-09-14  2022-10-14               1  No cancellation

   PlanType
0  Standard
1     Basic
2   Premium
3     Basic
4     Basic

--------------------------------------------------

DataFrame name: dfusers_data
   UserID Gender  Age   Location RegistrationDate
0       1      M   49         UK       2022-08-11
1       2      F   56  Australia       2022-09-07
2       3      M   49        USA       2022-05-27
3       4      M   21  Australia       2022-04-06
4       5      M   47         UK       2022-09-14

--------------------------------------------------

> **categorías de variables tipo 'object'**

In [7]:
# Análisis de categorías de variables tipo 'object'

for df in listadfs:
    print("\n" + "<>"*50 + "\n")
    print("DataFrame name:", df.name if hasattr(df, 'name') else "Unnamed DataFrame")
    
    for colcat in df.columns:
        if df[colcat].dtype == 'O':
            print("Variable: ", colcat)
            print("Categorías de la variable: ", df[colcat].unique())
            print("\n" + "-"*50 + "\n")

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfcac_merged_updated_data
Variable:  CampaignName
Categorías de la variable:  ['Social Media Blitz: Targeted ads on Instagram and Facebook'
 'YouTube Ads Campaign: Video ads for trending content'
 'Search Engine Marketing: Google and Bing keyword targeting'
 'Influencer Partnership: Promotions through popular creators'
 'Email Outreach: Targeted offers to existing prospects'
 'Mobile App Push: Notifications to dormant users'
 'TV Commercials: Prime-time ad slots'
 'Referral Program: Bonuses for user referrals'
 'Discount Promotion: 50% off first subscription month'
 'Content Marketing: Blog posts and SEO optimization']

--------------------------------------------------


<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfinteractions_data
Variable:  InteractionDate
Categorías de la variable:  ['2023-04-04' '2023-01-30' '2023-02-16' '2022-09-25' '2022-12-18'
 '2023-06-16' '2023-06-13' '2023-05-19' '2023-05-04' '2022-08-21'
 '2023-01-21' '2023-06-01' '2023-03-25' '2022-11-16' '2023-01-09'
 '2022-10-18' '2023-05-14' '2023-05-03' '2023-04-21' '2023-08-09'
 '2023-09-06' '2022-10-27' '2022-08-07' '2022-10-02' '2022-09-07'
 '2022-06-20' '2022-10-04' '2023-01-10' '2022-11-14' '2022-09-05'
 '2022-06-07' '2022-07-09' '2023-03-27' '2023-02-02' '2023-02-17'
 '2022-11-07' '2022-09-01' '2022-10-20' '2022-04-30' '2022-07-03'
 '2022-08-26' '2023-04-05' '2022-05-22' '2022-12-27' '2022-10-21'
 '2023-01-12' '2022-12-11' '2023-03-06' '2022-08-20' '2023-02-14'
 '2022-06-26' '2022-07-17' '2022-09-11' '2022-07-22' '2022-12-20'
 '2023-03-03' '2023-03-15' '2022-10-22' '2022-09-17' '2023-04-11'
 '2022-12-30' '2023-07-21' '2022-10-17' '2023-05-22' '2023-02-01'
 '2022-10-12' '2023-07-28' '2023-03-17' '2023-05-07' '2023-11-14'
 '2023-01-24' '2023-05-16' '2023-04-27' '2023-10-10' '2023-09-09'
 '2023-10-30' '2023-04-09' '2023-06-06' '2023-09-18' '2022-12-01'
 '2022-08-17' '2022-02-24' '2022-03-03' '2022-05-31' '2022-11-09'
 '2022-11-29' '2022-11-12' '2022-09-19' '2022-09-22' '2022-02-26'
 '2022-06-29' '2022-01-23' '2022-06-30' '2022-03-06' '2022-06-12'
 '2022-05-15' '2022-04-14' '2023-01-07' '2022-10-09' '2022-05-18'
 '2022-02-13' '2022-08-29' '2022-07-04' '2022-05-19' '2022-12-09'
 '2022-07-10' '2022-02-21' '2022-04-06' '2023-04-10' '2022-11-15'
 '2023-05-31' '2023-05-10' '2023-09-24' '2023-08-06' '2023-10-04'
 '2023-09-27' '2023-04-12' '2023-05-29' '2023-06-12' '2022-10-29'
 '2023-03-13' '2023-06-21' '2022-12-22' '2023-05-18' '2023-03-10'
 '2022-10-23' '2023-05-17' '2023-12-01' '2023-02-13' '2023-10-16'
 '2023-06-15' '2023-11-18' '2023-07-31' '2023-07-08' '2023-03-31'
 '2023-10-03' '2023-06-11' '2023-06-23' '2022-12-08' '2023-01-03'
 '2023-02-18' '2023-01-28' '2023-07-15' '2023-09-12' '2023-09-15'
 '2023-05-25' '2023-02-23' '2022-12-28' '2022-12-04' '2023-07-03'
 '2023-08-26' '2023-05-23' '2022-09-18' '2022-09-15' '2023-03-30'
 '2023-01-26' '2023-02-24' '2023-03-21' '2022-10-30' '2023-04-24'
 '2023-06-14' '2023-05-08' '2023-04-30' '2023-07-30' '2022-08-19'
 '2023-03-12' '2023-01-11' '2023-01-08' '2022-08-23' '2022-09-02'
 '2022-11-03' '2023-02-05' '2023-05-27' '2023-01-19' '2022-08-24'
 '2022-11-21' '2022-06-17' '2022-07-19' '2023-10-19' '2022-12-12'
 '2023-07-01' '2023-10-15' '2022-12-19' '2022-12-17' '2023-04-06'
 '2023-07-14' '2022-07-07' '2023-04-08' '2022-12-24' '2023-04-28'
 '2022-06-24' '2023-03-20' '2023-01-06' '2022-11-24' '2023-01-14'
 '2023-05-01' '2023-01-29' '2022-06-08' '2022-09-21' '2022-06-28'
 '2022-08-06' '2023-02-12' '2022-11-18' '2022-07-24' '2022-12-06'
 '2022-12-07' '2023-04-25' '2022-07-06' '2023-03-23' '2022-09-27'
 '2023-05-24' '2023-06-22' '2023-03-29' '2023-03-22' '2022-12-03'
 '2022-11-23' '2023-04-19' '2023-01-04' '2023-05-11' '2022-10-08'
 '2023-02-11' '2022-11-19' '2022-11-04' '2022-09-06' '2022-11-13'
 '2022-09-12' '2022-07-29' '2022-11-22' '2022-07-02' '2022-09-23'
 '2022-02-09' '2023-06-20' '2023-01-31' '2022-10-19' '2022-11-10'
 '2022-06-02' '2022-06-18' '2022-09-26' '2022-06-22' '2022-09-16'
 '2023-02-28' '2022-07-21' '2022-04-29' '2022-07-01' '2023-03-07'
 '2022-06-25' '2023-07-26' '2023-07-12' '2023-06-18' '2023-08-20'
 '2023-07-25' '2022-11-30' '2023-09-14' '2023-08-16' '2023-11-17'
 '2023-10-20' '2023-08-22' '2023-10-18' '2022-12-15' '2023-04-23'
 '2022-11-20' '2023-10-29' '2023-08-08' '2023-04-26' '2023-09-26'
 '2023-05-09' '2023-03-02' '2022-10-11' '2022-03-14' '2022-05-16'
 '2022-09-29' '2023-02-15' '2022-04-24' '2022-03-24' '2022-05-04'
 '2022-08-16' '2022-11-02' '2022-04-23' '2023-02-25' '2023-05-02'
 '2022-09-09' '2023-05-05' '2023-04-14' '2023-01-20' '2022-07-28'
 '2022-08-28' '2023-06-04' '2022-12-29' '2022-06-21' '2022-07-13'
 '2023-09-21' '2023-08-11' '2023-10-17' '2023-06-28' '2023-08-10'
 '2023-09-07' '2022-12-31' '2023-09-08' '2023-10-02' '2023-03-11'
 '2022-11-28' '2022-12-25' '2023-11-08' '2023-11-20' '2022-09-30'
 '2022-03-21' '2022-06-05' '2023-02-07' '2022-03-26' '2022-05-05'
 '2022-07-20' '2022-07-25' '2023-01-25' '2022-10-26' '2022-03-09'
 '2023-08-28' '2022-11-05' '2023-04-02' '2023-09-10' '2022-12-10'
 '2023-07-04' '2023-07-05' '2022-04-04' '2022-06-09' '2022-10-01'
 '2022-09-20' '2022-09-28' '2022-04-22' '2022-08-30' '2022-03-15'
 '2022-09-24' '2022-04-18' '2022-12-02' '2023-09-01' '2023-04-29'
 '2023-05-12' '2023-07-07' '2023-06-17' '2023-01-16' '2022-11-08'
 '2023-03-28' '2023-08-18' '2023-03-01' '2022-12-05' '2023-02-08'
 '2023-02-04' '2022-10-07' '2023-05-28' '2023-08-27' '2023-08-24'
 '2023-07-19' '2022-12-26' '2022-11-01' '2022-08-05' '2022-05-28'
 '2022-09-04' '2022-05-27' '2022-09-13' '2023-03-26' '2023-02-21'
 '2023-07-16' '2023-04-17' '2023-02-09' '2023-03-19' '2022-10-13'
 '2023-03-16' '2023-11-21' '2023-02-06' '2023-02-26' '2022-04-13'
 '2022-04-19' '2023-01-17' '2023-02-03' '2023-03-24' '2022-05-07'
 '2022-05-26' '2022-04-03' '2022-04-02' '2023-08-05' '2023-02-19'
 '2022-11-25' '2022-10-14' '2022-08-01' '2022-08-14' '2022-05-30'
 '2022-07-15' '2023-04-01' '2022-11-27' '2022-08-09' '2023-04-22'
 '2022-11-06' '2022-05-01' '2022-09-14' '2023-03-04' '2022-06-14'
 '2022-05-12' '2022-05-06' '2022-06-10' '2023-03-14' '2022-08-15'
 '2022-08-03' '2022-08-27' '2023-01-27' '2023-09-02' '2023-06-07'
 '2023-08-04' '2023-11-09' '2022-11-17' '2022-08-08' '2022-05-09'
 '2022-08-10' '2022-05-14' '2022-09-03' '2023-01-13' '2022-08-25'
 '2023-01-01' '2023-05-20' '2023-07-13' '2023-06-03' '2023-06-02'
 '2022-11-11' '2023-01-02' '2023-02-22' '2023-07-11' '2023-05-06'
 '2023-07-10' '2022-10-16' '2022-10-25' '2023-03-08' '2023-11-29'
 '2023-12-18' '2023-10-01' '2023-12-19' '2023-12-12' '2023-05-13'
 '2023-11-27' '2022-08-22' '2023-01-18' '2022-10-24' '2023-06-19'
 '2023-05-15' '2023-03-18' '2022-07-23' '2022-09-10' '2022-06-06'
 '2022-08-11' '2022-08-18' '2022-07-26' '2022-04-08' '2022-12-14'
 '2022-07-30' '2022-06-19' '2023-04-03' '2022-12-23' '2022-06-13'
 '2022-05-17' '2022-04-26' '2022-07-16' '2022-08-13' '2023-05-30'
 '2023-04-18' '2022-11-26' '2023-01-22' '2022-08-12' '2022-02-18'
 '2022-09-08' '2022-04-01' '2022-10-15' '2023-06-26' '2023-08-25'
 '2023-02-27' '2022-06-23' '2022-07-08' '2022-02-05' '2022-02-22'
 '2022-01-25' '2022-02-12' '2023-06-25' '2023-07-06' '2023-08-14'
 '2023-01-15' '2022-12-16' '2023-01-05' '2023-05-26' '2023-08-03'
 '2023-11-16' '2023-10-23' '2023-12-21' '2023-11-12' '2023-07-02'
 '2023-08-31' '2023-06-05' '2023-07-24' '2022-12-21' '2023-09-22'
 '2023-09-16' '2022-04-07' '2022-04-05' '2023-01-23' '2022-06-27'
 '2023-09-11' '2023-08-01' '2022-01-21' '2022-07-27' '2022-05-10'
 '2022-06-16' '2022-03-18' '2022-01-27' '2022-01-28' '2022-03-07'
 '2023-07-20' '2022-05-02' '2023-08-12' '2023-08-15' '2023-08-29'
 '2023-08-21' '2023-05-21' '2022-07-31' '2022-10-05' '2023-06-30'
 '2023-06-24' '2022-03-10' '2022-07-05' '2022-02-23' '2023-10-14'
 '2022-06-11' '2022-10-28' '2022-10-06' '2022-05-08' '2023-03-09'
 '2022-08-02' '2022-04-11' '2022-10-31' '2023-03-05' '2022-03-27'
 '2022-06-01' '2023-04-13' '2022-12-13' '2022-10-10' '2022-04-27'
 '2022-03-16' '2022-07-14' '2022-04-17' '2022-04-16' '2022-05-11'
 '2022-04-25' '2022-03-05' '2022-03-08' '2022-07-12' '2022-04-21'
 '2022-06-15' '2022-07-11' '2023-02-10' '2022-05-03' '2022-03-20'
 '2022-03-30' '2022-04-28' '2023-04-15' '2023-08-17' '2023-04-16'
 '2023-11-06' '2023-10-13' '2023-10-27' '2023-09-05' '2023-07-29'
 '2023-04-07' '2022-03-22' '2022-01-11' '2022-03-25' '2022-02-02'
 '2022-02-25' '2022-01-19' '2022-05-24' '2023-06-08' '2023-08-30'
 '2023-09-17' '2022-02-01' '2022-02-27' '2022-02-08' '2022-04-20'
 '2022-08-04' '2022-01-29' '2023-11-19' '2023-08-07' '2023-07-27'
 '2023-09-04' '2022-05-23' '2023-04-20' '2023-11-22' '2023-07-18'
 '2023-11-01' '2023-12-10' '2023-10-05' '2023-08-23' '2023-09-13'
 '2023-10-12' '2023-08-02' '2023-07-09' '2023-11-05' '2023-11-15'
 '2023-10-31' '2023-12-05' '2023-11-02' '2023-10-24' '2023-08-19'
 '2023-09-23' '2023-10-11' '2022-04-15' '2023-12-02' '2023-07-23'
 '2023-12-25' '2023-12-16' '2023-11-28' '2023-12-11' '2023-11-30'
 '2022-08-31' '2023-06-10' '2023-11-11' '2023-10-09' '2023-12-07'
 '2023-06-27' '2022-03-28' '2022-03-13' '2022-02-10' '2022-03-11'
 '2023-06-29' '2022-03-12' '2022-10-03' '2023-10-21' '2023-07-22'
 '2023-10-07' '2022-01-26' '2022-03-31' '2022-04-09' '2023-09-03'
 '2023-09-28' '2022-04-10' '2022-07-18' '2023-10-26' '2023-02-20'
 '2023-10-22' '2022-03-23' '2022-05-25' '2022-02-17' '2022-01-16'
 '2022-01-24' '2022-02-28' '2022-06-03' '2022-05-13' '2022-02-19'
 '2022-05-20' '2022-02-11' '2022-05-21' '2022-01-13' '2022-02-06'
 '2023-09-30' '2023-11-03' '2023-11-26' '2023-12-13' '2023-12-22']

--------------------------------------------------

Variable:  InteractionType
Categorías de la variable:  ['Content View' 'Help Request']

--------------------------------------------------

Variable:  ContentGenre
Categorías de la variable:  ['Thriller' 'Comedy' nan 'Drama' 'Documentary' 'Action' 'Horror' 'Romance']

--------------------------------------------------


<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfpayments_data
Variable:  PaymentDate
Categorías de la variable:  ['2022-08-11' '2022-09-10' '2022-10-10' '2022-11-09' '2022-12-09'
 '2023-01-08' '2023-02-07' '2023-03-09' '2023-04-08' '2023-05-08'
 '2023-06-07' '2023-07-07' '2023-08-06' '2023-09-05' '2023-10-05'
 '2023-11-04' '2023-12-04' '2024-01-03' '2024-02-02' '2024-03-03'
 '2024-04-02' '2024-05-02' '2022-09-07' '2022-10-07' '2022-11-06'
 '2022-12-06' '2023-01-05' '2023-02-04' '2023-03-06' '2023-04-05'
 '2023-05-05' '2023-06-04' '2023-07-04' '2023-08-03' '2023-09-02'
 '2023-10-02' '2023-11-01' '2023-12-01' '2023-12-31' '2024-01-30'
 '2024-02-29' '2024-03-30' '2024-04-29' '2022-05-27' '2022-06-26'
 '2022-07-26' '2022-08-25' '2022-04-06' '2022-09-14' '2022-10-14'
 '2022-11-21' '2022-12-21' '2023-01-20' '2023-02-19' '2023-03-21'
 '2023-04-20' '2023-05-20' '2023-06-19' '2022-01-04' '2022-02-03'
 '2022-03-05' '2022-04-04' '2022-05-04' '2022-06-03' '2022-07-03'
 '2022-08-02' '2022-09-01' '2022-10-01' '2022-10-31' '2022-11-30'
 '2022-12-30' '2023-01-29' '2023-02-28' '2022-01-16' '2022-02-15'
 '2022-03-17' '2022-04-16' '2022-05-16' '2022-12-02' '2023-01-01'
 '2023-01-31' '2023-03-02' '2023-04-01' '2023-05-01' '2023-05-31'
 '2023-06-30' '2022-09-04' '2022-10-04' '2022-11-03' '2022-12-03'
 '2023-01-02' '2023-02-01' '2023-03-03' '2022-09-15' '2022-10-15'
 '2022-11-14' '2022-12-14' '2023-01-13' '2023-02-12' '2023-03-14'
 '2023-04-13' '2023-05-13' '2023-06-12' '2023-07-12' '2023-08-11'
 '2023-09-10' '2023-10-10' '2022-06-09' '2022-07-09' '2022-08-08'
 '2022-06-01' '2022-07-01' '2022-07-31' '2022-08-30' '2022-09-29'
 '2022-10-29' '2022-11-28' '2022-12-28' '2023-01-27' '2023-02-26'
 '2023-03-28' '2023-04-27' '2023-05-27' '2023-06-26' '2023-07-26'
 '2023-08-25' '2023-09-24' '2023-10-24' '2022-06-27' '2022-07-27'
 '2022-08-26' '2022-09-25' '2022-10-25' '2022-11-24' '2022-12-24'
 '2022-06-12' '2022-07-12' '2022-02-02' '2022-03-04' '2022-04-03'
 '2022-05-03' '2022-06-02' '2022-07-02' '2022-08-01' '2022-08-31'
 '2022-09-30' '2022-10-30' '2022-11-29' '2022-12-29' '2022-06-28'
 '2022-07-28' '2022-08-27' '2022-09-26' '2022-10-26' '2022-11-25'
 '2022-12-25' '2023-01-24' '2023-02-23' '2023-03-25' '2023-04-24'
 '2023-05-24' '2023-06-23' '2023-07-23' '2023-08-22' '2022-04-11'
 '2022-05-11' '2022-06-10' '2022-07-10' '2022-08-09' '2022-09-08'
 '2022-10-08' '2022-11-07' '2022-12-07' '2023-01-06' '2023-02-05'
 '2023-03-07' '2023-04-06' '2023-05-06' '2023-06-05' '2023-07-05'
 '2023-08-04' '2023-09-03' '2023-10-03' '2023-11-02' '2023-01-23'
 '2023-02-22' '2023-03-24' '2023-04-23' '2023-05-23' '2023-06-22'
 '2023-07-22' '2023-08-21' '2023-09-20' '2023-10-20' '2023-11-19'
 '2023-12-19' '2022-11-19' '2022-12-19' '2023-01-18' '2023-02-17'
 '2023-03-19' '2023-04-18' '2023-05-18' '2023-06-17' '2022-03-06'
 '2022-04-05' '2022-05-05' '2022-06-04' '2022-07-04' '2022-08-03'
 '2022-09-02' '2022-10-02' '2022-11-01' '2022-12-01' '2022-12-31'
 '2023-01-30' '2023-03-01' '2023-03-31' '2023-04-30' '2023-05-30'
 '2023-06-29' '2023-07-29' '2023-08-28' '2023-09-27' '2023-10-27'
 '2023-11-26' '2023-12-26' '2022-06-17' '2022-07-17' '2022-08-16'
 '2023-11-09' '2023-12-09' '2024-01-08' '2024-02-07' '2024-03-08'
 '2024-04-07' '2022-11-26' '2022-12-26' '2023-01-25' '2023-02-24'
 '2023-03-26' '2023-04-25' '2023-05-25' '2022-02-12' '2022-03-14'
 '2022-02-13' '2022-03-15' '2022-04-14' '2022-05-14' '2022-06-13'
 '2022-07-13' '2022-08-12' '2022-09-11' '2022-10-11' '2022-11-10'
 '2022-12-10' '2023-01-09' '2023-02-08' '2023-03-10' '2023-04-09'
 '2023-05-09' '2023-06-08' '2023-07-08' '2023-08-07' '2022-10-12'
 '2022-11-11' '2022-12-11' '2023-01-10' '2023-02-09' '2023-03-11'
 '2023-04-10' '2023-05-10' '2023-06-09' '2022-01-12' '2022-02-11'
 '2022-03-13' '2022-04-12' '2022-05-12' '2022-06-11' '2022-07-11'
 '2022-08-10' '2022-09-09' '2022-10-09' '2022-11-08' '2022-12-08'
 '2023-01-07' '2023-02-06' '2023-03-08' '2023-04-07' '2023-05-07'
 '2023-06-06' '2022-02-04' '2024-01-25' '2024-02-24' '2024-03-25'
 '2024-04-24' '2024-05-24' '2023-04-02' '2023-05-02' '2023-06-01'
 '2023-07-01' '2023-07-31' '2023-08-30' '2023-09-29' '2023-10-29'
 '2023-11-28' '2023-12-28' '2024-01-27' '2024-02-26' '2022-03-31'
 '2022-04-30' '2022-05-30' '2022-06-29' '2022-07-29' '2022-08-28'
 '2022-09-27' '2022-10-27' '2022-09-21' '2022-10-21' '2022-11-20'
 '2022-12-20' '2023-01-28' '2023-02-27' '2023-03-29' '2023-04-28'
 '2023-05-28' '2023-06-27' '2023-07-27' '2023-08-26' '2023-09-25'
 '2023-06-24' '2023-07-24' '2023-08-23' '2023-09-22' '2023-10-22'
 '2023-11-21' '2022-04-25' '2022-05-25' '2022-06-24' '2022-07-24'
 '2022-08-23' '2022-09-22' '2022-10-22' '2022-04-15' '2022-07-15'
 '2022-08-14' '2022-09-13' '2022-10-13' '2022-11-12' '2022-12-12'
 '2023-01-11' '2023-02-10' '2023-03-12' '2023-04-11' '2023-05-11'
 '2023-06-10' '2023-07-10' '2023-08-09' '2023-09-08' '2023-10-08'
 '2023-11-07' '2023-12-07' '2024-01-06' '2023-09-06' '2023-10-06'
 '2023-11-05' '2023-12-05' '2024-01-04' '2024-02-03' '2024-03-04'
 '2024-04-03' '2024-05-03' '2024-06-02' '2024-07-02' '2024-08-01'
 '2022-04-24' '2022-05-24' '2022-06-23' '2022-07-23' '2022-08-22'
 '2022-03-16' '2022-05-15' '2022-06-14' '2022-07-14' '2022-08-13'
 '2022-09-12' '2023-07-09' '2023-08-08' '2022-08-05' '2022-09-06'
 '2022-10-06' '2022-11-05' '2022-12-05' '2023-01-04' '2023-02-03'
 '2022-12-23' '2023-01-22' '2023-07-06' '2023-08-05' '2023-09-04'
 '2022-08-15' '2022-04-09' '2022-05-09' '2022-06-08' '2022-07-08'
 '2022-08-07' '2022-02-05' '2022-03-07' '2022-05-06' '2022-06-05'
 '2022-07-05' '2022-08-04' '2022-09-03' '2022-10-03' '2022-11-02'
 '2023-07-30' '2023-08-29' '2023-09-28' '2023-10-28' '2022-05-31'
 '2022-06-30' '2022-07-30' '2022-08-29' '2022-09-28' '2022-10-28'
 '2022-11-27' '2022-12-27' '2022-02-06' '2022-03-08' '2022-04-07'
 '2022-05-07' '2022-06-06' '2022-07-06' '2023-10-25' '2022-01-13'
 '2022-04-13' '2022-05-13' '2023-03-05' '2023-04-04' '2023-05-04'
 '2023-06-03' '2023-07-03' '2023-01-26' '2023-02-25' '2023-03-27'
 '2023-04-26' '2023-05-26' '2023-06-25' '2024-02-05' '2024-03-06'
 '2024-04-05' '2024-05-05' '2024-06-04' '2023-11-24' '2023-12-24'
 '2024-01-23' '2024-02-22' '2024-03-23' '2024-04-22' '2022-03-03'
 '2022-04-02' '2022-05-02' '2022-03-25' '2023-01-19' '2023-02-18'
 '2023-03-20' '2023-04-19' '2023-05-19' '2023-06-18' '2023-07-18'
 '2023-08-17' '2023-09-16' '2023-10-16' '2023-11-15' '2023-12-15'
 '2024-01-14' '2023-10-04' '2023-11-03' '2023-12-03' '2024-01-02'
 '2024-02-01' '2024-03-02' '2024-04-01' '2024-05-01' '2024-05-31'
 '2024-06-30' '2024-07-30' '2024-08-29' '2022-01-19' '2022-02-18'
 '2022-03-20' '2022-04-19' '2022-05-19' '2022-06-18' '2022-07-18'
 '2022-08-17' '2022-09-16' '2022-10-16' '2022-11-15' '2022-09-24'
 '2022-10-24' '2022-11-23' '2023-02-21' '2023-03-23' '2023-04-22'
 '2023-05-22' '2023-06-21' '2023-07-21' '2023-08-20' '2023-09-19'
 '2023-10-19' '2022-04-10' '2022-05-10' '2022-08-21' '2022-09-20'
 '2022-10-20' '2022-06-15' '2023-07-19' '2023-08-18' '2023-09-17'
 '2023-10-17' '2023-11-16' '2022-07-25' '2022-08-24' '2022-09-23'
 '2022-10-23' '2022-11-22' '2022-12-22' '2023-01-21' '2023-02-20'
 '2023-03-22' '2023-04-21' '2023-05-21' '2023-06-20' '2023-07-20'
 '2023-08-19' '2023-09-18' '2022-02-21' '2022-03-23' '2022-04-22'
 '2022-05-22' '2022-06-21' '2022-07-21' '2022-08-20' '2022-09-19'
 '2022-10-19' '2022-11-18' '2022-12-18' '2023-01-17' '2023-02-16'
 '2023-03-18' '2023-04-17' '2023-05-17' '2023-08-02' '2022-03-10'
 '2023-09-01' '2023-10-01' '2023-10-31' '2023-11-30' '2022-01-25'
 '2022-02-24' '2022-03-26' '2022-02-22' '2022-03-24' '2022-04-23'
 '2022-05-23' '2022-06-22' '2022-07-22' '2023-07-17' '2023-08-16'
 '2022-02-26' '2022-03-28' '2022-04-27' '2022-02-08' '2022-12-15'
 '2023-11-23' '2023-12-23' '2024-01-22' '2023-12-02' '2024-01-01'
 '2024-01-31' '2024-03-01' '2024-03-31' '2024-04-30' '2023-07-25'
 '2023-08-24' '2023-09-23' '2023-10-23' '2023-11-22' '2022-05-26'
 '2022-06-25' '2023-09-21' '2023-10-21' '2023-11-20' '2023-12-20'
 '2024-01-19' '2024-02-18' '2024-03-19' '2024-04-18' '2024-05-18'
 '2024-06-17' '2022-01-09' '2024-06-01' '2024-07-01' '2022-08-18'
 '2022-09-17' '2022-10-17' '2022-11-16' '2022-12-16' '2023-01-15'
 '2023-02-14' '2023-03-16' '2023-04-15' '2023-05-15' '2022-01-07'
 '2022-05-21' '2022-06-20' '2022-07-20' '2022-08-19' '2022-09-18'
 '2022-10-18' '2022-11-17' '2022-12-17' '2023-01-16' '2022-06-19'
 '2022-07-19' '2023-06-14' '2023-07-14' '2023-08-13' '2023-09-12'
 '2023-10-12' '2023-11-11' '2023-12-11' '2024-01-10' '2024-02-09'
 '2024-03-10' '2024-04-09' '2022-01-05' '2022-01-29' '2022-02-28'
 '2022-03-30' '2022-04-29' '2022-05-29' '2023-02-15' '2023-03-17'
 '2023-04-16' '2023-05-16' '2023-06-15' '2023-12-16' '2024-01-15'
 '2023-06-16' '2023-07-16' '2023-08-15' '2023-09-14' '2023-10-14'
 '2023-11-13' '2023-12-13' '2024-01-12' '2024-02-11' '2024-03-12'
 '2024-04-11' '2022-03-11' '2023-03-30' '2023-04-29' '2023-05-29'
 '2023-06-28' '2023-07-28' '2023-08-27' '2023-09-26' '2023-10-26'
 '2023-11-25' '2023-12-25' '2022-06-16' '2022-07-16' '2022-11-13'
 '2022-12-13' '2023-01-12' '2023-02-11' '2023-03-13' '2023-04-12'
 '2023-05-12' '2023-06-11' '2023-07-11' '2023-08-10' '2023-09-09'
 '2023-10-09' '2023-11-08' '2022-04-01' '2022-05-01' '2023-01-14'
 '2023-02-13' '2023-03-15' '2023-04-14' '2023-05-14' '2023-07-15'
 '2023-08-14' '2023-09-13' '2022-02-27' '2022-03-29' '2022-04-28'
 '2022-05-28' '2023-12-22' '2024-01-21' '2024-02-20' '2024-03-21'
 '2024-04-20' '2022-01-01' '2022-01-31' '2022-03-02' '2023-11-18'
 '2023-09-15' '2022-03-21' '2022-04-20' '2022-05-20' '2023-06-13'
 '2023-07-13' '2023-08-12' '2023-09-11' '2023-10-11' '2023-11-10'
 '2023-12-10' '2024-01-09' '2024-02-08' '2024-03-09' '2022-01-20'
 '2022-02-19' '2022-02-16' '2022-03-18' '2022-04-17' '2022-05-17'
 '2023-10-15' '2023-11-14' '2023-12-14' '2024-01-13' '2022-01-14'

> **¿qué dataframes tienen varias filas por UserID?**

- dfitneractions_data
- dfpayments_data

In [8]:
# Revisar qué dataframes tienen varias filas por UserID

for df in listadfs:
    print("DataFrame name:", df.name if hasattr(df, 'name') else "Unnamed DataFrame")
    print(df.groupby("UserID").size().sort_values(ascending = False).head(10))
    print("\n" + "<>"*50 + "\n")

DataFrame name: dfcac_merged_updated_data
UserID
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
dtype: int64

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfinteractions_data
UserID
65     29
22     29
178    29
133    29
57     28
41     28
10     28
13     28
196    28
150    28
dtype: int64

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfpayments_data
UserID
23     23
35     23
24     23
196    23
110    23
114    23
120    23
73     23
174    23
186    23
dtype: int64

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfsubscriptions_data
UserID
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
dtype: int64

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfusers_data
UserID
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
dtype: int64

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

In [9]:
# Revisar qué dataframes tienen varias filas por UserID
for df in listadfs:
    print("DataFrame name:", df.name if hasattr(df, 'name') else "Unnamed DataFrame")
    if df.UserID.nunique() == df.shape[0]:
        print("✅ El dataframe tiene -sólo 1 fila- por cada UserID")
    else:
        print("🔂 El dataframe tiene -filas repetidas- por cada UserID")
    print("\n" + "<>"*50 + "\n")

DataFrame name: dfcac_merged_updated_data
✅ El dataframe tiene -sólo 1 fila- por cada UserID

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfinteractions_data
🔂 El dataframe tiene -filas repetidas- por cada UserID

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfpayments_data
🔂 El dataframe tiene -filas repetidas- por cada UserID

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfsubscriptions_data
✅ El dataframe tiene -sólo 1 fila- por cada UserID

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

DataFrame name: dfusers_data
✅ El dataframe tiene -sólo 1 fila- por cada UserID

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

> **Registros vacíos de `dfinteractions_data.ContentGenre`**

- Los 1.704 registros con `ContentGenre == nan`, corresponden a los 1.704 registros con `InteractionType == "Help Request"`, por lo tanto, son válidos.

In [10]:
dfinteractions_data["InteractionType"].value_counts()

InteractionType
Content View    1726
Help Request    1704
Name: count, dtype: int64

In [11]:
dfinteractions_data["ContentGenre"].groupby(dfinteractions_data["InteractionType"]).value_counts(dropna= False)

InteractionType  ContentGenre
Content View     Horror           266
                 Documentary      260
                 Thriller         254
                 Comedy           247
                 Romance          240
                 Action           234
                 Drama            225
Help Request     NaN             1704
Name: count, dtype: int64

# 3. Construcción de Dataframe único de usuarios

## 3.1. Ajuste variables de fecha (--Date)

In [12]:
# InteractionDate es un objeto, lo convertimos a datetime

dfinteractions_data["InteractionDate"] = pd.to_datetime(dfinteractions_data["InteractionDate"], errors='coerce')
dfinteractions_data["InteractionDate"].dtype

dtype('<M8[ns]')

In [13]:
# PaymentDate es un objeto, lo convertimos a datetime

dfpayments_data["PaymentDate"] = pd.to_datetime(dfpayments_data["PaymentDate"], errors='coerce')
dfpayments_data["PaymentDate"].dtype

dtype('<M8[ns]')

In [14]:
# EndDate es un objeto, lo convertimos a datetime

dfsubscriptions_data["EndDate"] = pd.to_datetime(dfsubscriptions_data["EndDate"], errors='coerce')
dfsubscriptions_data["EndDate"].dtype

dtype('<M8[ns]')

In [15]:
# dfsubscriptions_data["RegistrationDate"] es un objeto, lo convertimos a datetime

dfsubscriptions_data["RegistrationDate"] = pd.to_datetime(dfsubscriptions_data["RegistrationDate"], errors='coerce')
dfsubscriptions_data["RegistrationDate"].dtype

dtype('<M8[ns]')

In [16]:
# dfusers_data["RegistrationDate"] es un objeto, lo convertimos a datetime

dfusers_data["RegistrationDate"] = pd.to_datetime(dfusers_data["RegistrationDate"], errors='coerce')
dfusers_data["RegistrationDate"].dtype

dtype('<M8[ns]')

## 3.1. Agregación de interacciones y pagos a nivel -Usuario-

> ***`dfinteractions_data`***

Nuevo dataframe: `dfinteractions_peruser`, con las columnas:

- UserID
- total_interactions
- number_helprqs
- number_contentviews
- mostly_viewedgenre
- first_contentviewdate
- last_contentviewdate
- first_helprqsdate
- last_helprqsdate

In [31]:
# Creamos columnas temporales con la fecha solo si cumple la condición

dfinteractions_data['Date_ContentView'] = dfinteractions_data['InteractionDate'].where(dfinteractions_data['InteractionType'] == 'Content View', pd.NaT)
dfinteractions_data['Date_HelpRequest'] = dfinteractions_data['InteractionDate'].where(dfinteractions_data['InteractionType'] == 'Help Request', pd.NaT)

In [32]:
# 1. Creamos una columna temporal que concatene el género con el número de vistas, solo para las filas que son 'Content View'
dfinteractions_data['Interaccion_Genero'] = 'number_views_genre' + dfinteractions_data['ContentGenre'].astype(str)

# Si volviste a correr la celda, eliminamos las columnas viejas para que no choquen
dfinteractions_data = dfinteractions_data.drop(columns=[c for c in dfinteractions_data.columns if 'number_views_genre' in c], errors='ignore')

# 2. Creamos columnas booleanas (0 y 1) SOLO para las filas que son 'Content View'
# Las filas que NO son 'Content View' se llenan con 0 de forma segura
dummies = pd.get_dummies(dfinteractions_data.loc[dfinteractions_data['InteractionType'] == 'Content View', 'Interaccion_Genero']).astype(int)
dfinteractions_data = dfinteractions_data.join(dummies)
dfinteractions_data[dummies.columns] = dfinteractions_data[dummies.columns].fillna(0).astype(int)

# 3. Guardamos los nombres de las nuevas columnas dinámicas para sumarlas en el agg del groupby
columnas_genero = list(dummies.columns)

# Creamos las agregaciones de género dinámicamente con un ciclo for (comprensión de diccionario)
dinamicas = {col: (col, 'sum') for col in columnas_genero}

In [33]:
dfinteractions_peruser = dfinteractions_data.groupby("UserID").agg(
    total_interactions = ("InteractionDate", "count"),
    number_helprqs = ('InteractionType', lambda x: (x == 'Help Request').sum()),
    number_contentviews = ('InteractionType', lambda x: (x == 'Content View').sum()),
    first_contentviewdate=('Date_ContentView', 'min'),
    last_contentviewdate=('Date_ContentView', 'max'),
    first_helprqsdate=('Date_HelpRequest', 'min'),
    last_helprqsdate=('Date_HelpRequest', 'max'),
    **dinamicas # Agrega dinámicamente las columnas de género al agg del groupby
).reset_index()

# El operador ** (desempaquetado de diccionarios) toma las claves y valores del diccionario "dinamicas" 
# y se los entrega a .agg() como si los hubieras escrito manualmente uno por uno dentro de los paréntesis

In [34]:
print(dfinteractions_peruser.info(), "\n")

print(dfinteractions_peruser.head(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   UserID                         200 non-null    int64
 1   total_interactions             200 non-null    int64
 2   number_helprqs                 200 non-null    int64
 3   number_contentviews            200 non-null    int64
 4   first_contentviewdate          199 non-null    datetime64[ns]
 5   last_contentviewdate           199 non-null    datetime64[ns]
 6   first_helprqsdate              199 non-null    datetime64[ns]
 7   last_helprqsdate               199 non-null    datetime64[ns]
 8   number_views_genreAction       200 non-null    int64
 9   number_views_genreComedy       200 non-null    int64
 10  number_views_genreDocumentary  200 non-null    int64
 11  number_views_genreDrama        200 non-null    int64
 12  number_views_genreHorror       200 non-null    int64
 13  number_views_genreRomance      200 non-null    int64
 14  number_views_genreThriller     200 non-null    int64
dtypes: datetime64[ns](4), int64(11)
memory usage: 23.6 KB
None

   UserID  total_interactions  number_helprqs  number_contentviews  \
0       1                  16               9                    7
1       2                   5               4                    1
2       3                  13               5                    8
3       4                  21              10                   11
4       5                  17               7                   10
5       6                  14               8                    6
6       7                  17               7                   10
7       8                  17               7                   10
8       9                  23               7                   16
9      10                  28              14                   14

  first_contentviewdate last_contentviewdate first_helprqsdate  \
0            2022-11-16           2023-06-16        2022-08-21
1            2023-09-06           2023-09-06        2023-04-21
2            2022-06-07           2023-04-21        2022-09-05
3            2022-06-26           2023-03-06        2022-04-30
4            2022-09-17           2023-07-28        2022-10-12
5            2023-02-01           2023-09-09        2022-12-01
6            2022-02-26           2022-11-29        2022-01-23
7            2022-02-13           2022-12-09        2022-02-21
8            2022-11-15           2023-10-04        2022-10-23
9            2022-12-08           2023-12-01        2022-12-18

  last_helprqsdate  number_views_genreAction  number_views_genreComedy  \
0       2023-06-01                         1                         1
1       2023-08-09                         0                         1
2       2023-01-10                         2                         0
3       2023-04-05                         0                         2
4       2023-03-17                         1                         1
5       2023-11-14                         0                         1
6       2022-11-12                         4                         1
7       2023-01-07                         2                         0
8       2023-07-28                         2                         2
9       2023-11-18                         2                         3

   number_views_genreDocumentary  number_views_genreDrama  \
0                              1                        1
1                              0                        0
2                              0                        2
3                              0                        0
4                              2                        2
5                              0                        2
6                              0                        0
7                              2                        0
8                              2                        2
9                              2                        2

   number_views_genreHorror  number_views_genreRomance  \
0                         1                          0
1                         0                          0
2                         1                          1
3                         4                          4
4                         0                          1
5                         1                          0
6                         3                          1
7                         2                          2
8                         2                          2
9                         1                          3

   number_views_genreThriller
0                           2
1                           0
2                           2
3                           1
4                           3
5                           2
6                           1
7                           2
8                           4
9                           1

In [43]:
# Guardar en csv en la carpeta de datos procesados
dfinteractions_peruser.to_csv("../data/processed/interactions_per_user.csv", index=False)

> ***`dfpayments_data`***

Nuevo dataframe: `dfpayments_peruser`, con las columnas:

- UserID
- total_payments
- first_payment_date
- last_payment_date
- first_payment_amount
- last_payment_amount

In [ ]:
# ordenamos el df de pagos por UserID y PaymentDate para que las funciones first y last del groupby 
# agarren la fecha correcta
dfpayments_data.sort_values(by=['UserID', 'PaymentDate'], inplace=True)

In [36]:
dfpayments_data["PaymentDate"].dtype

dtype('<M8[ns]')

In [37]:
dfpayments_peruser = dfpayments_data.groupby("UserID").agg(
     total_payments = ("PaymentDate", "count"),
     first_payment_date = ("PaymentDate", "min"),
     last_payment_date = ("PaymentDate", "max"),
     first_payment_amount = ("PaymentAmount", "first"), # sobre el df ordenado por PaymentDate, no por UserID
     last_payment_amount = ("PaymentAmount", "last") # sobre el df ordenado por PaymentDate, no por UserID
     ).reset_index()

In [38]:
print(dfpayments_peruser.info(), "\n")

print(dfpayments_peruser.head(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   UserID                200 non-null    int64
 1   total_payments        200 non-null    int64
 2   first_payment_date    200 non-null    datetime64[ns]
 3   last_payment_date     200 non-null    datetime64[ns]
 4   first_payment_amount  200 non-null    float64
 5   last_payment_amount   200 non-null    float64
dtypes: datetime64[ns](2), float64(2), int64(2)
memory usage: 9.5 KB
None

   UserID  total_payments first_payment_date last_payment_date  \
0       1              22         2022-08-11        2024-05-02
1       2              21         2022-09-07        2024-04-29
2       3               4         2022-05-27        2022-08-25
3       4               1         2022-04-06        2022-04-06
4       5               2         2022-09-14        2022-10-14
5       6               8         2022-11-21        2023-06-19
6       7              15         2022-01-04        2023-02-28
7       8               5         2022-01-16        2022-05-16
8       9               7         2022-10-07        2023-04-05
9      10               8         2022-12-02        2023-06-30

   first_payment_amount  last_payment_amount
0                  9.99                 9.99
1                 19.99                19.99
2                  9.99                 9.99
3                  9.99                 9.99
4                 15.99                15.99
5                 19.99                19.99
6                 15.99                15.99
7                 15.99                15.99
8                 19.99                19.99
9                 19.99                19.99

In [44]:
# Guardar en csv en la carpeta de datos procesados
dfpayments_peruser.to_csv("../data/processed/dfpayments_peruser.csv", index=False)

## 3.2. merge de dataframes

> 1. Usar `functools.reduce` (La forma "profesional")

Esta es la forma estándar de unir una lista de DataFrames. reduce toma una función (en este caso `pd.merge`) y la aplica sucesivamente a los elementos de tu lista.

In [45]:
from functools import reduce

In [46]:
# Lista de los DataFrames
dfs = [dfusers_data, # datos de usuarios
       dfsubscriptions_data, # datos de suscripciones
       dfpayments_peruser, # datos de pagos por usuario
       dfcac_merged_updated_data, # datos de Costo de adquisición CAC
       dfinteractions_peruser] # datos de interacciones por usuario (vistas y help requests)

# Unirlos todos usando una columna común ('UserID', partiendo del data frame de usuarios)
df_netflixmerge = reduce(lambda left, right: pd.merge(left, right, on='UserID', how='left'), dfs)

In [47]:
df_netflixmerge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   UserID                         200 non-null    int64
 1   Gender                         200 non-null    object
 2   Age                            200 non-null    int64
 3   Location                       200 non-null    object
 4   RegistrationDate_x             200 non-null    datetime64[ns]
 5   RegistrationDate_y             200 non-null    datetime64[ns]
 6   EndDate                        200 non-null    datetime64[ns]
 7   DurationMonths                 200 non-null    int64
 8   CancelReason                   200 non-null    object
 9   PlanType                       200 non-null    object
 10  total_payments                 200 non-null    int64
 11  first_payment_date             200 non-null    datetime64[ns]
 12  last_payment_date              200 non-null    datetime64[ns]
 13  first_payment_amount           200 non-null    float64
 14  last_payment_amount            200 non-null    float64
 15  CampaignID                     200 non-null    int64
 16  CampaignName                   200 non-null    object
 17  CampaignCost                   200 non-null    int64
 18  UsersAcquired                  200 non-null    int64
 19  CAC                            200 non-null    float64
 20  total_interactions             200 non-null    int64
 21  number_helprqs                 200 non-null    int64
 22  number_contentviews            200 non-null    int64
 23  first_contentviewdate          199 non-null    datetime64[ns]
 24  last_contentviewdate           199 non-null    datetime64[ns]
 25  first_helprqsdate              199 non-null    datetime64[ns]
 26  last_helprqsdate               199 non-null    datetime64[ns]
 27  number_views_genreAction       200 non-null    int64
 28  number_views_genreComedy       200 non-null    int64
 29  number_views_genreDocumentary  200 non-null    int64
 30  number_views_genreDrama        200 non-null    int64
 31  number_views_genreHorror       200 non-null    int64
 32  number_views_genreRomance      200 non-null    int64
 33  number_views_genreThriller     200 non-null    int64
dtypes: datetime64[ns](9), float64(3), int64(17), object(5)
memory usage: 53.3+ KB

In [48]:
# visualizamos el df final para asegurarnos que se haya unido correctamente
df_netflixmerge

,UserID,Gender,Age,Location,RegistrationDate_x,RegistrationDate_y,EndDate,DurationMonths,CancelReason,PlanType,...,last_contentviewdate,first_helprqsdate,last_helprqsdate,number_views_genreAction,number_views_genreComedy,number_views_genreDocumentary,number_views_genreDrama,number_views_genreHorror,number_views_genreRomance,number_views_genreThriller
0,1,M,49,UK,2022-08-11,2022-08-11,2022-12-09,4,No cancellation,Standard,...,2023-06-16,2022-08-21,2023-06-01,1,1,1,1,1,0,2
1,2,F,56,Australia,2022-09-07,2022-09-07,2024-02-29,18,No cancellation,Basic,...,2023-09-06,2023-04-21,2023-08-09,0,1,0,0,0,0,0
2,3,M,49,USA,2022-05-27,2022-05-27,2023-02-21,9,No cancellation,Premium,...,2023-04-21,2022-09-05,2023-01-10,2,0,0,2,1,1,2
3,4,M,21,Australia,2022-04-06,2022-04-06,2024-01-26,22,No cancellation,Basic,...,2023-03-06,2022-04-30,2023-04-05,0,2,0,0,4,4,1
4,5,M,47,UK,2022-09-14,2022-09-14,2022-10-14,1,No cancellation,Basic,...,2023-07-28,2022-10-12,2023-03-17,1,1,2,2,0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,F,54,Canada,2022-12-24,2022-12-24,2023-10-20,10,No cancellation,Standard,...,2023-12-13,2023-01-21,2023-12-22,3,0,2,1,3,1,1
196,197,F,41,USA,2022-06-05,2022-06-05,2022-08-04,2,No cancellation,Basic,...,2023-05-07,2022-06-25,2023-05-04,3,2,0,1,2,0,2
197,198,F,46,Australia,2022-01-08,2022-01-08,2022-07-07,6,Lack of use,Premium,...,2022-09-22,2022-04-17,2022-12-10,0,0,0,0,1,1,0
198,199,M,63,Canada,2022-05-02,2022-05-02,2024-01-22,21,No cancellation,Basic,...,2023-04-10,2022-06-14,2023-04-10,1,1,1,0,0,1,1
199,200,M,48,Australia,2022-12-14,2022-12-14,2023-06-12,6,Cost,Standard,...,2023-09-23,2023-03-16,2023-07-21,0,1,1,0,0,0,0

In [49]:
# Guardar en csv en la carpeta de datos procesados
df_netflixmerge.to_csv("../data/processed/df_netflixmerge.csv", index=False)

# 4. Feature Engineering

> **Nuevas variables:**

- `lifetimevalue` = (total_payments)*(last_payment_amount) -> Dado que no cambiaron los valores pagados en el tiempo.
- `ltvcac_ratio` = round(lifetimevalue / CAC, 2)
- `netcustomervalue` = lifetimevalue - CAC
- `churned` = 0 if Cancellation == 'no cancellation' else 1

> **Nuevas variables dummies (*one hot encoding*)**

- `gender`
- `location`
- `CancelReason`
- `PlanType`

In [51]:
# Creamos una copia del df final para hacerle transformaciones sin perder el original

df_netflixfinal = df_netflixmerge.copy()

df_netflixfinal.columns

Index(['UserID', 'Gender', 'Age', 'Location', 'RegistrationDate_x',
       'RegistrationDate_y', 'EndDate', 'DurationMonths', 'CancelReason',
       'PlanType', 'total_payments', 'first_payment_date', 'last_payment_date',
       'first_payment_amount', 'last_payment_amount', 'CampaignID',
       'CampaignName', 'CampaignCost', 'UsersAcquired', 'CAC',
       'total_interactions', 'number_helprqs', 'number_contentviews',
       'first_contentviewdate', 'last_contentviewdate', 'first_helprqsdate',
       'last_helprqsdate', 'number_views_genreAction',
       'number_views_genreComedy', 'number_views_genreDocumentary',
       'number_views_genreDrama', 'number_views_genreHorror',
       'number_views_genreRomance', 'number_views_genreThriller'],
      dtype='object')

In [53]:
df_netflixfinal["CancelReason"].unique()

array(['No cancellation', 'Lack of use', 'Cost', 'Switched provider'],
      dtype=object)

In [54]:
# Nuevas variables

try:
    df_netflixfinal["lifetimevalue"] = round(df_netflixfinal["total_payments"] * df_netflixfinal["last_payment_amount"], 2)

    df_netflixfinal["ltvcac_ratio"] = round(df_netflixfinal["lifetimevalue"] / df_netflixfinal["CAC"], 2)

    df_netflixfinal["netcustomervalue"] = round(df_netflixfinal["lifetimevalue"] - df_netflixfinal["CAC"], 2)

    df_netflixfinal["churned"] = np.where(df_netflixfinal["CancelReason"] == "No cancellation", 0, 1)

    print("✅ Nuevas variables creadas exitosamente.")

except KeyError as e:
    print(f"🚩 Error: La columna {e} no se encuentra en el DataFrame. Asegúrate de que todas las columnas necesarias estén presentes.")

✅ Nuevas variables creadas exitosamente.

In [55]:
df_netflixfinal.columns

Index(['UserID', 'Gender', 'Age', 'Location', 'RegistrationDate_x',
       'RegistrationDate_y', 'EndDate', 'DurationMonths', 'CancelReason',
       'PlanType', 'total_payments', 'first_payment_date', 'last_payment_date',
       'first_payment_amount', 'last_payment_amount', 'CampaignID',
       'CampaignName', 'CampaignCost', 'UsersAcquired', 'CAC',
       'total_interactions', 'number_helprqs', 'number_contentviews',
       'first_contentviewdate', 'last_contentviewdate', 'first_helprqsdate',
       'last_helprqsdate', 'number_views_genreAction',
       'number_views_genreComedy', 'number_views_genreDocumentary',
       'number_views_genreDrama', 'number_views_genreHorror',
       'number_views_genreRomance', 'number_views_genreThriller',
       'lifetimevalue', 'ltvcac_ratio', 'netcustomervalue', 'churned'],
      dtype='object')

> **OneHotEncoding**

In [60]:
# One hot encoding

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# 1. Definir las columnas que queremos transformar
categorical_features = ['Gender', 'Location', 'CancelReason', 'PlanType']

# 2. Configurar el transformador

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(sparse_output=False, # para que devuelva un array denso y no una matriz dispersa
                              handle_unknown='ignore', # para que no de error si aparece una categoría nueva en el futuro
                              drop='first'), # para evitar la multicolinealidad, se puede elegir una categoría de referencia para cada variable y eliminarla del resultado final
                              categorical_features) # lista de columnas a transformar
    ],
    remainder='passthrough', # Mantiene las columnas que no fueron transformadas
    verbose_feature_names_out = False # Para que los nombres de las columnas salgan sin el prefijo del transformador ('cat__', 'remainder__')
)

# 3. Aplicar la transformación
# Esto devuelve un array de NumPy
data_encoded = preprocessor.fit_transform(df_netflixfinal)

# 4. Convertir de nuevo a DataFrame para mantener los nombres de las columnas
# Obtenemos los nuevos nombres de las columnas generadas
feature_names = preprocessor.get_feature_names_out()

df_final = pd.DataFrame(data_encoded, columns=feature_names)

In [61]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 43 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender_M                        200 non-null    object
 1   Location_Canada                 200 non-null    object
 2   Location_UK                     200 non-null    object
 3   Location_USA                    200 non-null    object
 4   CancelReason_Lack of use        200 non-null    object
 5   CancelReason_No cancellation    200 non-null    object
 6   CancelReason_Switched provider  200 non-null    object
 7   PlanType_Premium                200 non-null    object
 8   PlanType_Standard               200 non-null    object
 9   UserID                          200 non-null    object
 10  Age                             200 non-null    object
 11  RegistrationDate_x              200 non-null    datetime64[ns]
 12  RegistrationDate_y              200 non-null    datetime64[ns]
 13  EndDate                         200 non-null    datetime64[ns]
 14  DurationMonths                  200 non-null    object
 15  total_payments                  200 non-null    object
 16  first_payment_date              200 non-null    datetime64[ns]
 17  last_payment_date               200 non-null    datetime64[ns]
 18  first_payment_amount            200 non-null    object
 19  last_payment_amount             200 non-null    object
 20  CampaignID                      200 non-null    object
 21  CampaignName                    200 non-null    object
 22  CampaignCost                    200 non-null    object
 23  UsersAcquired                   200 non-null    object
 24  CAC                             200 non-null    object
 25  total_interactions              200 non-null    object
 26  number_helprqs                  200 non-null    object
 27  number_contentviews             200 non-null    object
 28  first_contentviewdate           199 non-null    datetime64[ns]
 29  last_contentviewdate            199 non-null    datetime64[ns]
 30  first_helprqsdate               199 non-null    datetime64[ns]
 31  last_helprqsdate                199 non-null    datetime64[ns]
 32  number_views_genreAction        200 non-null    object
 33  number_views_genreComedy        200 non-null    object
 34  number_views_genreDocumentary   200 non-null    object
 35  number_views_genreDrama         200 non-null    object
 36  number_views_genreHorror        200 non-null    object
 37  number_views_genreRomance       200 non-null    object
 38  number_views_genreThriller      200 non-null    object
 39  lifetimevalue                   200 non-null    object
 40  ltvcac_ratio                    200 non-null    object
 41  netcustomervalue                200 non-null    object
 42  churned                         200 non-null    object
dtypes: datetime64[ns](9), object(34)
memory usage: 67.3+ KB

In [62]:
df_final.head(10)

,Gender_M,Location_Canada,Location_UK,Location_USA,CancelReason_Lack of use,CancelReason_No cancellation,CancelReason_Switched provider,PlanType_Premium,PlanType_Standard,UserID,...,number_views_genreComedy,number_views_genreDocumentary,number_views_genreDrama,number_views_genreHorror,number_views_genreRomance,number_views_genreThriller,lifetimevalue,ltvcac_ratio,netcustomervalue,churned
0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1,...,1,1,1,1,0,2,219.78,3.48,156.56,0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2,...,1,0,0,0,0,0,419.79,6.64,356.57,0
2,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,3,...,0,0,2,1,1,2,39.96,0.63,-23.26,0
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4,...,2,0,0,4,4,1,9.99,0.16,-53.23,0
4,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,5,...,1,2,2,0,1,3,31.98,0.51,-31.24,0
5,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,6,...,1,0,2,1,0,2,159.92,2.53,96.7,0
6,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,7,...,1,0,0,3,1,1,239.85,3.79,176.63,1
7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,8,...,0,2,0,2,2,2,79.95,1.26,16.73,1
8,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,9,...,2,2,2,2,2,4,139.93,2.21,76.71,0
9,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,10,...,3,2,2,1,3,1,159.92,2.53,96.7,0

In [63]:
# Guardar en csv en la carpeta de datos procesados
df_final.to_csv("../data/processed/df_final.csv", index=False)

In [66]:
df_final[df_final["churned"] == 1].shape[0]

54